---
glob: "app/**/*.erb"
EnableDefaultLinters: true
linters:
  CommentSyntax:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      require:
        - standard
        - rubocop-rails
        - rubocop-performance
      inherit_gem:
        standard: config/ruby-3.3.yml
        standard-rails: config/base.yml
        standard-performance: config/base.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/LeadingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/CommentIndentation:
        Enabled: false
